### ISSUE TITLE
Http 2.0

### ISSUE THREAD

**Issue by arthurnn** [jnunemaker/httparty#379]
Is there any plans on supporting http 2.0 protocol on http party? Or should we create a httparty2?
thanks

**Comment by jnunemaker** [comment]
I'm mostly just maintaining httparty at this point. I haven't thought about http 2.0. Honestly, I haven't really followed along with the http 2 conversation so I don't know how easy or hard it would be to support both.

**Comment by Dschee** [comment]
Maybe [this](http://chimera.labs.oreilly.com/books/1230000000545/ch12.html) is worth a read for you then. @jnunemaker

**Comment by corvinb** [comment]
+1  Any update on this?  I want to upgrade my app to make requests using HTTP/2 and I am looking for solutions.  I'd prefer a simple gem update.  :)

**Comment by jnunemaker** [comment]
No update other than if someone wants to start a PR, I'm open to looking it over. My main concerns are I'm not interested in breaking backwards compatibility and I'd prefer to stay on top of ruby's standard libraries. If ruby supports http2 (again I haven't looked into any of this at all) then perhaps we should look into it. If not, then I guess there is no update.

**Comment by TheSmartnik** [comment]
As `HTTTParty` is build on top of `Net::HTTP` I don't think it's possible to implement HTTP/2 in `HTTParty`. HTTP/2 completely different protocol similar only in name. It's both binary and async, both of which is impossible to implement in `HTTParty`.

Plus, I don't really see any benefit to it. HTTP/2 is justifiable only in the context of browser, where it's possible to have dozens (or better hundenders) of simultaneous requests to the same host. Otherwise, you won't see any benefit in speed. Additionally, server must support HTTP/2, which is not be the case for many websites.

If you need to create multiple simultaneous requests, you can just use threads, as I said difference in speed for the same host will be milliseconds compared to HTTP/2
