### ISSUE TITLE
Always redirects to port 80

### ISSUE THREAD

**Issue by stevegraham** [jnunemaker/httparty#396]
See https://github.com/jnunemaker/httparty/blob/166e8822a977e626346c9510b6126ba4f5fa6afc/lib/httparty/request.rb#L81

Correct implementation is

```ruby
class HTTParty::Request
  def base_uri
    redirect ? "#{@last_uri.scheme}://#{@last_uri.host}:#{@last_uri.port}" : options[:base_uri]
  end
end
```

**Comment by anothermh** [comment]
+1 on this. Rails runs on port 3000, this is making all my redirects fail to work because it's interpreting it as pointing to port 80.

The following endpoint performs an action and then calls a `redirect`. It should redirect to localhost:3000 and instead is redirecting to localhost:80.

```
url = 'http://localhost:3000/api/v1/endpoint'
options = {}
HTTParty.put(url, options)
```

returns:

`Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 80`
