### ISSUE TITLE
Response#failure?

### ISSUE THREAD

**Issue by georgeu2000** [jnunemaker/httparty#456]
A `response` responds to `success?`, but not `failure?`

I would be happy to do a pull request, but did not see how `success?` is defined.

Failure would be 4xx or 5xx.

I don't know if failure is the same as `! success?`. If success is 2xx, then they are indeed very different and it would be a useful feature.

**Comment by jnunemaker** [comment]
The httparty response is just a thin wrapper over net/http's response. success? is defined by net/http and failure? is not. That is why failure? doesn't exist. I'm not sure I want to add something that ruby itself isn't using. Closing the issue, but open for more discussion if you want to convince me otherwise (in which case I'll re-open). :)

**Comment by georgeu2000** [comment]
I tried using net/http `response.success?` and it does not seem to be defined. 

I didn't find any documentation on it: http://ruby-doc.org/stdlib-2.2.3/libdoc/net/http/rdoc/Net/HTTPResponse.html

I did not find it defined in https://github.com/ruby/ruby/blob/trunk/lib/net/http/response.rb.

Do you know where it is defined?

**Comment by jstrater** [comment]
It's been a few years since you asked the question, but for the benefit of anyone Googling this, httparty defines the `success?` method [here](https://github.com/jnunemaker/httparty/blob/99751ac98af929b315c74c2ac0f5ffa09195f7ae/lib/httparty/response.rb#L56L65).

The code I linked above defines predicate methods for all of the response classes -- for example, `Response#server_error?` for `5xx Server Error` responses, `#redirection?` for `3xx Redirection`, and `#success?` for `2xx Success`. It also defines them for specific response codes, like `#unauthorized?` for `401 Unauthorized`. You can find them all listed in the [Net::HTTP docs](https://www.rubydoc.info/stdlib/net/Net/HTTPResponse) under `CODE_TO_OBJ` and `CODE_CLASS_TO_OBJ`.

**Comment by ivan-uqido** [comment]
@jstrater the link to the httparty method seems to point to the wrong thing, doesn't it?

**Comment by ttilberg** [comment]
It's the right place in the code, it's just not necessarily obvious. I just had to work through the same thing, and that comment helped point right to the class names I was hoping to find.

I'll break it down here for future party goers:

The linked code:
```rb
    CODES_TO_OBJ = ::Net::HTTPResponse::CODE_CLASS_TO_OBJ.merge ::Net::HTTPResponse::CODE_TO_OBJ

    CODES_TO_OBJ.each do |response_code, klass|
      name = klass.name.sub("Net::HTTP", '')
      name = "#{underscore(name)}?".to_sym

      define_method(name) do
        klass === response
      end
    end
```

[Net::HTTPResponse::CODE_CLASS_TO_OBJ](https://www.rubydoc.info/stdlib/net/Net/HTTPResponse#CODE_CLASS_TO_OBJ-constant): This maps "classes" of codes to... classes.. of ... code.. (🤔 ):
  - 100 series codes: Information
  - 200 series: Success
  - 300 series: Redirection
  - 400 series: Client Error
  - 500 series: server error

[Net::HTTPResponse::CODE_TO_OBJ](https://www.rubydoc.info/stdlib/net/Net/HTTPResponse#CODE_TO_OBJ-constant)`: This maps specific HTTP codes to NetHTTP classes:
  - 200: Ok
  - 302: Found
  - 500: Internal Server Error

The HTTParty code iterates over these two NetHTTP mappings to build predicate methods for each one using the NetHTTP response class to define the method:

<img width="991" alt="image" src="https://user-images.githubusercontent.com/7969650/193048579-9a2bc4c2-e351-4ebd-a85e-002e05de6899.png">

They are all implemented as "is the response of this known Net::HTTP class?"

This has been helpful to understand. I often get confused with "Should I use `ok?` or `success?`?" Knowing that it maps "code classes" and "codes" to predicate methods will probably help me in the future. Or at least, maybe I'll remember where to look next time.
