### ISSUE TITLE
EOFError on simple request?

### ISSUE THREAD

**Issue by Meekohi** [jnunemaker/httparty#594]
Simple request results in this error. Works fine with curl, in browser, etc... doesn't seem to be any hints at what's going on?
```
> HTTParty.get("http://ticketfly.com/api/events/upcoming.json?venueId=3677")
EOFError: end of file reached
```

```
httparty (0.16.2)
Rails 5.2.0
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
```

**Comment by Meekohi** [comment]
Works fine with Faraday fwiw:
```
> Faraday.get "http://ticketfly.com/api/events/upcoming.json?venueId=3677"
 => #<Faraday::Response:0x007fcb9c1efb80 ...>
```

**Comment by anothermh** [comment]
That error comes from Net::HTTP which is why you don't get the same error with Faraday:

    HTTParty.get("http://ticketfly.com/api/events/upcoming.json?venueId=3677")
    EOFError: end of file reached
    from /Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:189:in `rbuf_fill'

The relevant method from `protocol.rb`:

    def rbuf_fill
      case rv = @io.read_nonblock(BUFSIZE, exception: false)
      when String
        @rbuf << rv
        rv.clear
        return
      when :wait_readable
        @io.to_io.wait_readable(@read_timeout) or raise Net::ReadTimeout
        # continue looping
      when :wait_writable
        # OpenSSL::Buffering#read_nonblock may fail with IO::WaitWritable.
        # http://www.openssl.org/support/faq.html#PROG10
        @io.to_io.wait_writable(@read_timeout) or raise Net::ReadTimeout
        # continue looping
      when nil
        raise EOFError, 'end of file reached'
      end while true
    end

In this case `@io.read_nonblock` is returning `nil`. The `@io` object is an `TCPSocket` object so we aren't even at the right layer for HTTP to be a consideration.

I wanted to test the JSON payload to be sure there wasn't anything wrong with it so I wrote a simple Rails controller to get the payload with Faraday and re-render it:

    class TestController < ApplicationController
      def foo
        render json: Faraday.get('http://ticketfly.com/api/events/upcoming.json?venueId=3677').body
      end
    end

Then I ran `HTTParty.get('http://localhost:3000')` and Net::HTTP successfully retrieves the data.

Since the issue is happening at the TCP socket several layers down from HTTP, and since it can't be replicated with the same payload from a local server, I'm inclined to think it might be a remote server issue.

Do you have any examples of this behavior from a different server? Or do you have any examples from this same server that do not generate the EOF exception? Without further examples I'm not sure that I can learn anymore about what's happening.

**Comment by Meekohi** [comment]
Heya, not sure if it will help but their API documentation is at https://www.ticketfly.com/files/2010/10/ticketfly-event-api-20101011.pdf

Other examples (all cause same issue):
http://www.ticketfly.com/api/events/list.json?orgId=3677
http://www.ticketfly.com/api/events/onsale.json?orgId=3677

Interestingly, even `HTTParty.get("http://ticketfly.com/api")` causes the issue, so I agree it is related to something with the server response. Maybe makes sense to just close this if it's down in the TCP layer.

**Comment by TheSmartnik** [comment]
@Meekohi it's a bug on ticketfly's side. Their response doesn't end with `\r\n` which basically violates http standard.

I think `net/http` could still work with this, though. `Content-Length` is correct, so potentially it could terminate based on content-length, but anyway it's definitely not a problem of `httparty`

**Comment by TheSmartnik** [comment]
@Meekohi Ok, I made a bit more digging into this. I was wrong in a previous comment.

The true reason is super funny, imho.  Apparently, ticketfly block requests with a word `ruby` in a user agent and send absolutely nothing in response.

So work around is super simple, just change user agent.
```ruby
HTTParty.get("http://ticketfly.com/api", headers: { "User-Agent" => "Why would you block rby agent? Come on" })
```

**Comment by anothermh** [comment]
Confirmed that it's the user agent:

    Faraday.default_connection = Faraday.new(options = {:headers=>{:user_agent=>'ruby'}})
    Faraday.get('http://ticketfly.com/api/events/upcoming.json?venueId=3677')
    Faraday::ConnectionFailed: end of file reached

**Comment by Meekohi** [comment]
Wow. 🤣🤣🤣
