### ISSUE TITLE
HTTParty multipart doesn't support changing of content-type

### ISSUE THREAD

**Issue by pangtongs** [jnunemaker/httparty#595]
In using multipart of HTTParty, the content-type of the file we opened will be hardcoded to be  using `Content-Type: application/octet-stream`.

However, there are cases where we want to send data with the different content-type, let's say we want to specify a jpg image and thus requires it to be `Content-Type: image/jpg`.

This case is currently not supported by the HTTParty system.

**Comment by jnunemaker** [comment]
Can you provide an example of how you are attempting to use content type?

**Comment by zherr** [comment]
👋 Just stumbled across this issue when making the jump from [httmultiparty](https://github.com/jwagener-soundcloud/httmultiparty) (now no longer maintained) to HTTParty's support for multipart requests.

We ran into an issue where an API we communicate with is expecting the `Content-Type` of the `multipart/form-data` data in the request to be set to the known media type. For example, uploading a `.png` file, the client would set the `Content-Type` to `image/png`.

We wanted to make sure this wasn't just a bug in the API we were using, so we did a little research. Specifically, we were using [this API call](https://developer.atlassian.com/cloud/jira/platform/rest/#api-api-2-issue-issueIdOrKey-attachments-post), which references [RFC 1867](https://www.ietf.org/rfc/rfc1867.txt), which was suspiciously experimental. We found a more updated specification ([RFC 2388](https://www.ietf.org/rfc/rfc2388.txt)) that confirms the expected behavior of the client:

>If the contents of a file are returned via filling out a form, then the file input is identified as the appropriate media type, if known, or "application/octet-stream".

So after all that, HTTParty should set the appropriate `Content-Type` of a multipart request if it knows how to. 

Overall this looks like a great addition to HTTParty. I'm guessing this new behavior should be implemented in a way that is backward-compatible and adds an option to determine the mime type. 

What does everyone else think?

[The old library we used](https://github.com/paracycle/httmultiparty/blob/f5073a369cb35629bf9fbaa88c1abed878e4e93b/lib/httmultiparty.rb#L22) harnessed a library called [mimemagic](https://github.com/minad/mimemagic). The (now deprecated) [paperclip library](https://github.com/thoughtbot/paperclip/blob/7edb35a2a9a80c9598dfde235c7e593c023fc914/lib/paperclip/content_type_detector.rb#L71) used it, and the more recent ActiveStorage solution for Rails [implemented a library called marcel ](https://github.com/rails/rails/pull/31693)(which just uses mimemagic under the hood).

**Comment by jdraths** [comment]
I spent some time chasing this issue. I know that it's not always desirable to add another dependency like `mimemagic`, so I put together some code that would work with and without `mimemagic`:

```ruby

def generate_multipart
  normalized_params = params.flat_map { |key, value| HashConversions.normalize_keys(key, value) }

  multipart = normalized_params.inject('') do |memo, (key, value)|
    memo += "--#{boundary}\r\n"
    memo += %(Content-Disposition: form-data; name="#{key}")
    # value.path is used to support ActionDispatch::Http::UploadedFile
    # https://github.com/jnunemaker/httparty/pull/585
    memo += %(; filename="#{File.basename(value.path)}") if file?(value)
    memo += "\r\n"
    if file?(value)
      ######################################
      ##### PROPOSED CHANGES START HERE #####
      ######################################
      # 1. check if 'ruby-mime-types' gem is 'required' in system
      if defined?(MimeMagic)
        puts 'MimeMagic is currently required'
        ctype = MimeMagic.by_magic(value).type
      elsif which("file")
        # 2. OR - try to use unix 'file' shell command
        # `file --mime -b "#{file.path}"`.chomp
        ctype = `file --mime -b "#{value.path}"`.chomp
      else
        # 3. OR revert to original httparty usage
        ctype = "application/octet-stream"
      end
      memo += "Content-Type: #{ctype}\r\n"
    end
    memo += "\r\n"
    memo += file?(value) ? value.read : value.to_s
    memo += "\r\n"
  end

  multipart += "--#{boundary}--\r\n"
end

# from https://stackoverflow.com/a/5471032/2628223
# to check if command exists
def which(cmd)
  exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : ['']
  ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
    exts.each { |ext|
      exe = File.join(path, "#{cmd}#{ext}")
      return exe if File.executable?(exe) && !File.directory?(exe)
    }
  end
  return nil
end

```


See my fork [here](https://github.com/jdraths/httparty/blob/master/lib/httparty/request/body.rb)

**Comment by TheSmartnik** [comment]
> file we opened will be hardcoded to be using Content-Type: application/octet-stream

@pangtongs @jnunemaker this was intentional, I neither wanted to add any new dependency, nor implementing MIME detection from scratch. I didn't know whether it was important at all as testing with rack proved to working correctly with any type of file.

I'd be happy to start discussion regarding the issue. In my opinion, the most efficient approach would be to use [mime-types](https://rubygems.org/gems/mime-types/versions/3.1) as [rest-client does](https://github.com/rest-client/rest-client/blob/master/lib/restclient/payload.rb#L186)

**Comment by jnunemaker** [comment]
@TheSmartnik mime-types seems fine. It has more downloads than httparty so it is probably more widely used already anyway.

**Comment by jdraths** [comment]
@TheSmartnik @jnunemaker The only thing I didn't like about `mime-types` is that it uses the [file name extension](https://github.com/mime-types/ruby-mime-types/blob/99268aec294903e7d15a3aa8fbc8f4dff077e445/lib/mime/types.rb#L139) to detect the mime type rather than the file content like `mime-magic`. Though, I suppose that's getting pretty far into the fringe.

**Comment by rahulbdominic** [comment]
@TheSmartnik I opened issue #614 which seems to be slightly related to this issue. I'd be glad to open a PR which adds `mime-types` as `rest-client` does it. That is what I had in mind.
