### ISSUE TITLE
Duplicate headers when symbols are passed without default headers

### ISSUE THREAD

**Issue by ehaynes99** [jnunemaker/httparty#629]
The fix for #472 turns symbol keys into strings. However, the fix does not cover the case where there are no default headers due to the conditional:
`if options[:headers] && headers.any?`

Example:
```ruby
HTTParty.post(
  'http://example.com',
  body: '{"test":"payload"}',
  headers: {
    'Content-Type': 'application/json',
  },
  debug_output: $stdout,
)
```
Output:
```
<- "POST / HTTP/1.1\r\nContent-Type: application/json\r\nConnection: close\r\nHost: example.com\r\nContent-Length: 18\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n"
<- "{\"test\":\"payload\"}"
```

**Comment by dmarkow** [comment]
It's not just duplicating the header, it's adding a different content type. So if you specify `application/json`, it includes it and ADDs an `application/x-www-form-urlencoded` content type as well. Because of the multiple content type requests, my API server is not recognizing my requests as application/json anymore.

For now, using `"Content-Type" => "application/json"` instead of `"Content-Type": "application/json"` resolves this for me.
