### ISSUE TITLE
Using empty path for specifik base_uri and queries gives an extra '/' before '?'

### ISSUE THREAD

**Issue by fhojdegard** [jnunemaker/httparty#727]
In our project we tried to update HTTParty to the latest. (0.16.2 -> 0.18.1) and our query request for one endpoint APIs stoped working because the request for empty path insist on adding a '/'.

```
class SomeWhereApi
  include HTTParty
  base_uri https://something_made_up.com/v1/end_point.jsp'

  def ask_api
    query = { limit: 10 }
    response = self.class.get('', query: query)
  end
end
```

Our log say:
[httplog] GET https://something_made_up.com/v1/end_point.jsp/?limit=10
And the request only work for
[httplog] GET https://something_made_up.com/v1/end_point.jsp?limit=10

Found that the slash comes from (httparty/request:74) from the `.normalize`
```
def path=(uri)
      uri_adapter = options[:uri_adapter]

      @path = if uri.is_a?(uri_adapter)
        uri
      elsif String.try_convert(uri)
        uri_adapter.parse(uri).normalize
      else
        raise ArgumentError,
          "bad argument (expected #{uri_adapter} object or URI string)"
      end
    end
```

**Comment by jnunemaker** [comment]
I’d say this is probably intended behavior. I can’t say I ever intended
base_uri to include the file and extension. It’s more of a protocol,
host and path thing. 

If there is a backwards compatible way to make it work for you I think
I’d be ok merging that. 

Probably would need to check if extension and if so then avoid the
trailing slash. 

Any thoughts on that?

On May 3, 2021, David Grevink ***@***.***> wrote:
> In our project we tried to update HTTParty to the latest. (0.16.2 ->
> 0.18.1) and our query request for one endpoint APIs stoped working
> because the request for empty path insist on adding a '/'.
>
> class SomeWhereApi include HTTParty base_uri
> https://something_made_up.com/v1/end_point.jsp' def ask_api query = {
> limit: 10 } response = self.class.get('', query: query) end end
> Our log say:
>  [httplog] GET
> https://something_made_up.com/v1/end_point.jsp/?limit=10
>  And the request only work for
>  [httplog] GET https://something_made_up.com/v1/end_point.jsp?limit=10
>
> Found that the slash comes from (httparty/request:74) from the
> .normalize
>
> def path=(uri) uri_adapter = options[:uri_adapter] @path = if
> uri.is_a?(uri_adapter) uri elsif String.try_convert(uri)
> uri_adapter.parse(uri).normalize else raise ArgumentError, "bad
> argument (expected #{uri_adapter} object or URI string)" end end

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jnunemaker/httparty/issues/727>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAAB22YC5GDH2XBLII5S5DTL2PNZANCNFSM44AZ33GQ>.

**Comment by fhojdegard** [comment]
Yes, I agree that we need to look over how we use Httparty. And that it probably should be from example:

```
base_uri 'https://something_made_up.com'
...
response = self.class.get('/v1/end_point.jsp', query: query)
```

What I don't agree with or understand is that path is turned from empty string '' to '/'. Especially with a query.
`self.class.get('', query: query) => https://something_made_up.com/?limit=10`

In the other cases the path is not magically changed.
`self.class.get('v1/end_point.jsp', query: query) => SocketError: getaddrinfo: Name or service not known`
and extra after gives expected.
` self.class.get('/v1/end_point.jsp/', query: query) => https://something_made_up.com/?limit=10`

With this pointed out, I don't know if you need to verify if base_uri includes extensions to avoid adding a trailing '/'. Do not see a reason why there should be one unless it is actually stated like:
```
self.class.get('/v1/end_point.jsp/')
or
self.class.get('/')
```
Thanks for feedback and response Httparty team.

**Comment by jnunemaker** [comment]
I was on vacation. Thus the long delay. Dug into this tonight. It's the uri adapter stuff. 

https://github.com/jnunemaker/httparty/blob/868053fce788e63dd48733d347cb15baa8c8ba74/lib/httparty/request.rb#L76

The default uri adapter is `URI`. This is URI's behavior:

```
irb(main):002:0> URI.parse("http://foo.com")
=> #<URI::HTTP http://foo.com>
irb(main):003:0> URI.parse("http://foo.com").to_s
=> "http://foo.com"
irb(main):004:0> URI.parse("http://foo.com").normalize.to_s
=> "http://foo.com/"
```

If you set your own uri adapter you should be able to make this work however you want. Let me know if that doesn't help you down the right path.

**Comment by fmichaut-diff** [comment]
For anyone else that has to deal with a very strict API, here is a simple workaround :
```ruby
class SomeWhereApi
  include HTTParty
  base_uri https://something_made_up.com/v1/end_point.jsp'

  def do_smth(body)
    self.post(URI.parse("?WSDL"), body:)
  end
end
```

Just pass an un-normalised `URI`, since the passed param only gets normalized if it is a string, and used as-is if a `URI`.
`URI.parse("?WSDL").normalize.to_s` holds `/?WSDL` while `URI.parse("?WSDL").to_s` hold `?WSDL`.

Hope this helps !
