### ISSUE TITLE
It is possible to encode UTF-8 for special characters in debug_output?

### ISSUE THREAD

**Issue by BrunoNelli** [jnunemaker/httparty#730]
Hi!

I'm trying to make some debug_output more legible encoding them to UTF-8 but i didn't find anything about this problem:
 
 
![image](https://user-images.githubusercontent.com/28799200/127051137-bdd68962-3430-47d3-9b9e-592ca26cbcd3.png)

As you can see, inside the variable @request the return is correct with special characters: ": o valor informado está inválido.",

 but in debugging/stdout_output the message is ": o valor informado est\xC3\xA1 inv\xC3\xA1lido.\"
 
 It is possible to configure the debug_output encoding to UTF-8?

**Comment by jnunemaker** [comment]
`debug_output` just gets passed to net/http. 

https://github.com/jnunemaker/httparty/blob/fb7c40303b7e6429196ef748754505768520407c/lib/httparty.rb#L227-L229

I googled a bit and stumbled on [this](https://stackoverflow.com/questions/24195185/specify-character-encoding-for-nethttp). I don't know much about encoding, but anything possible with net/http is possible with httparty because its just a thin layer on top.

Closing to keep things tidy but happy to keep responding if I can help.
