### ISSUE TITLE
Configured timeout is duplicated 

### ISSUE THREAD

**Issue by carlosramone** [jnunemaker/httparty#755]
As you can see, I configured 10 seconds of timeout. But it takes 20 seconds to throw the timeout exception.

```
require 'httparty'

class TimeoutHttparty
    include HTTParty

    default_timeout 10
    #open_timeout 1
    #read_timeout 10
    #write_timeout 1

    def test 
        puts('Start at: ' + Time.now.to_s)
        self.class.get("http://www.firebase.io")
        puts('End at: ' + Time.now.to_s)
    rescue StandardError => e
        puts('End with error at: ' + Time.now.to_s)
        puts e.message
    end
end

timeout = TimeoutHttparty.new
timeout.test
```

![image](https://user-images.githubusercontent.com/60460409/178403426-81edac37-4b29-456b-a901-eddb346a59f4.png)

**Comment by jnunemaker** [comment]
Probably retrying either in httparty or in the level below automatically in net/http. Also read timeout can take longer because I think it's the time between bytes read so as long as a trickle of data is being read it can go longer.

**Comment by carlosramone** [comment]
I'm not sure if it's httparty or net/http, but whatever timeout is set is doubled. I will keep checking.

**Comment by Ruslan** [comment]
This is net/http feature to retry requests

https://github.com/ruby/ruby/blob/v2_7_6/lib/net/http.rb#L762

it can be fixed in HTTParty like this:

```ruby
Benchmark.measure { HTTParty.get('http://httpstat.us/200?sleep=50000&q=', timeout: 10) rescue nil } 
# @real=20.28650915599428,

Benchmark.measure { HTTParty.get('http://httpstat.us/200?sleep=50000&q=', timeout: 10, max_retries: 0) rescue nil } 
# @real=10.168669935999787,
```

So if you have time-limited workflow with blocking http GET requests, it's better to set max_retries to 0 to avoid our current request timeout. This is really dangerous hidden feature in some cases (some vendors have non-idempotent GET requests)
